/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'stefan' at '8/13/15 4:47 PM' with Gradle 2.5
 *
 * @author stefan, @date 8/13/15 4:47 PM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
