/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'stefan' at '8/15/15 3:36 PM' with Gradle 2.6
 *
 * @author stefan, @date 8/15/15 3:36 PM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
