/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'stefan' at '8/13/15 4:47 PM' with Gradle 2.5
 *
 * @author stefan, @date 8/13/15 4:47 PM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
